services:
  mysql-db:
    image: mysql:8.0.33
    container_name: openJarvis-documenter
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  minio:
    image: minio/minio:RELEASE.2023-09-04T19-57-37Z
    container_name: openjarvis-documenter-object-storage
    ports:
      - "9000:9000"  # Porta da API S3
      - "9001:9001"  # Porta do Console Web
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  mysql_data:
  minio_data: